// packages/xstate-angular/src/useSelector.ts
import { ActorRef, SnapshotFrom } from 'xstate';
import { computed, Signal, signal } from '@angular/core';

function defaultCompare<T>(a: T, b: T) {
  return a === b;
}

export function useSelector<TActor extends ActorRef<any, any> | undefined, T>(
  actor: TActor,
  selector: (
    snapshot: TActor extends ActorRef<any, any>
      ? SnapshotFrom<TActor>
      : undefined
  ) => T,
  compare: (a: T, b: T) => boolean = defaultCompare
): Signal<T> {
  const actorRefRef = signal(actor);
  return computed(
    () => {
      const actorRef = actorRefRef();
      const snapshot = actorRef?.getSnapshot();
      return selector(snapshot);
    },
    { equal: compare }
  );
}

// packages/xstate-react/src/useSelector.ts
import { useCallback } from 'react';
import { useSyncExternalStoreWithSelector } from 'use-sync-external-store/shim/with-selector';
import { ActorRef, SnapshotFrom } from 'xstate';

function defaultCompare<T>(a: T, b: T) {
  return a === b;
}

export function useSelector<TActor extends ActorRef<any, any>, T>(
  actor: TActor,
  selector: (emitted: SnapshotFrom<TActor>) => T,
  compare: (a: T, b: T) => boolean = defaultCompare
): T {
  const subscribe = useCallback(
    (handleStoreChange) => {
      const { unsubscribe } = actor.subscribe(handleStoreChange);
      return unsubscribe;
    },
    [actor]
  );

  const boundGetSnapshot = useCallback(() => actor.getSnapshot(), [actor]);

  const selectedSnapshot = useSyncExternalStoreWithSelector(
    subscribe,
    boundGetSnapshot,
    boundGetSnapshot,
    selector,
    compare
  );

  return selectedSnapshot;
}
