// packages/xstate-solid/src/useSelector.ts
import type { ActorRef, Subscribable } from 'xstate';
import { defaultGetSnapshot } from './useActor';
import type { Accessor } from 'solid-js';
import { createEffect, createSignal, onCleanup, onMount } from 'solid-js';

const defaultCompare = (a, b) => a === b;

export function useSelector<
  TActor extends ActorRef<any>,
  T,
  TEmitted = TActor extends Subscribable<infer Emitted> ? Emitted : never
>(
  actor: TActor,
  selector: (emitted: TEmitted) => T,
  compare: (a: T, b: T) => boolean = defaultCompare,
  getSnapshot: (a: TActor) => TEmitted = defaultGetSnapshot
): Accessor<T> {
  const [selected, setSelected] = createSignal(selector(getSnapshot(actor)));

  const updateSelectedIfChanged = (nextSelected: T) => {
    if (!compare(selected(), nextSelected)) {
      setSelected(() => nextSelected);
    }
  };
  createEffect(() => {
    updateSelectedIfChanged(selector(getSnapshot(actor)));
  });
  let sub;
  onMount(() => {
    updateSelectedIfChanged(selector(getSnapshot(actor)));
    sub = actor.subscribe((emitted) => {
      updateSelectedIfChanged(selector(emitted));
    });
  });

  onCleanup(() => {
    sub?.unsubscribe();
  });

  return selected;
}

// packages/xstate-react/src/useSelector.ts
import { useCallback } from 'react';
import { useSyncExternalStoreWithSelector } from 'use-sync-external-store/shim/with-selector';
import { ActorRef, SnapshotFrom, Subscribable } from 'xstate';

function defaultCompare<T>(a: T, b: T) {
  return a === b;
}

export function useSelector<
  TActor extends Pick<ActorRef<any>, 'getSnapshot' | 'subscribe'>,
  T
>(
  actor: TActor,
  selector: (emitted: SnapshotFrom<TActor>) => T,
  compare: (a: T, b: T) => boolean = defaultCompare
): T {
  const subscribe = useCallback(
    (handleStoreChange) => {
      const { unsubscribe } = actor.subscribe(handleStoreChange);
      return unsubscribe;
    },
    [actor]
  );

  const boundGetSnapshot = useCallback(() => {
    if (!actor) {
      return;
    }
    return actor.getSnapshot();
  }, [actor]);

  const selectedSnapshot = useSyncExternalStoreWithSelector(
    subscribe,
    boundGetSnapshot,
    boundGetSnapshot,
    selector,
    compare
  );

  return selectedSnapshot;
}
