// examples/template-svelte-js/src/App.svelte
<script>
  import { useMachine } from '@xstate/svelte';
  import { toggleMachine } from './toggle.machine.js';

  const { state, send } = useMachine(toggleMachine);

  $: active = $state.matches('active');
  $: ({ count } = $state.context);
</script>

<main>
  <h1>XState Svelte Template</h1>
  <h2>Fork this template!</h2>
  <button on:click={() => send('TOGGLE')}>
    Click me ({active ? '✅' : '❌'})
  </button>
  <code>
    Activated <strong>{count}</strong> times
  </code>
</main>

<style>
  main {
    font-family: Avenir, Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-align: center;
    padding: 3rem 1rem;
    margin: 0 auto;
    color: #2c3e50;
  }
  button {
    margin-right: 0.5rem;
  }
  code {
    font-family: source-code-pro, Menlo, Monaco, Consolas, 'Courier New',
      monospace;
  }
</style>

// examples/template-vue-ts/src/App.vue
<template>
  <div id="app">
    <h1>XState Vue 3 Template</h1>
    <h2>Fork this template!</h2>
    <button @click="send('TOGGLE')">
      Click me ({{ state.matches("active") ? "✅" : "❌" }})
    </button>
    <code>
      Toggled
      <strong>{{ state.context.count }}</strong> times
    </code>
  </div>
</template>


<script lang="ts">
import { defineComponent } from 'vue'
import { useMachine } from '@xstate/vue';
import { toggleMachine } from "./toggle.machine";

export default defineComponent({
  name: 'App',
  setup() {
    const { state, send } = useMachine(toggleMachine);
    return {
      state,
      send,
    };
  }
})
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
