// docs/sandboxes/todomvc/Todo.jsx
import React, { useEffect, useRef } from "react";
import { useMachine } from "./useMachine";
import { todoMachine } from "./todoMachine";
import cn from "classnames";

export function Todo({ todo, onChange, onDelete, onComplete }) {
  const inputRef = useRef(null);
  const [state, send] = useMachine(
    todoMachine.withConfig(
      {
        actions: {
          focusInput() {
            setTimeout(() => {
              inputRef.current && inputRef.current.select();
            }, 0);
          },
          notifyDeleted(ctx) {
            onDelete(ctx.id);
          },
          notifyChanged(ctx) {
            onChange({
              id: ctx.id,
              title: ctx.title,
              completed: ctx.completed
            });
          }
        }
      },
      todo // extended state
    )
  );

  useEffect(
    () => {
      if (todo.completed !== completed) {
        // "Completed" changed externally... ugh.
        // React needs Actors.
        send("TOGGLE_COMPLETE");
      }
    },
    [todo]
  );

  const { completed, title } = state.context;

  return (
    <li
      className={cn({
        editing: state.matches("editing"),
        completed: completed
      })}
      data-todo-state={completed ? "completed" : "active"}
      key={todo.id}
    >
      <div className="view">
        <input
          className="toggle"
          type="checkbox"
          onChange={_ => {
            send("TOGGLE_COMPLETE");
          }}
          value={completed}
          checked={completed}
        />
        <label
          onDoubleClick={e => {
            send("EDIT");
          }}
        >
          {title}
        </label>{" "}
        <button className="destroy" onClick={() => send("DELETE")} />
      </div>
      <input
        className="edit"
        value={title}
        onBlur={_ => send("BLUR")}
        onChange={e => send({ type: "CHANGE", value: e.target.value })}
        onKeyPress={e => {
          if (e.key === "Enter") {
            send("COMMIT");
          }
        }}
        onKeyDown={e => {
          if (e.key === "Escape") {
            send("CANCEL");
          }
        }}
        ref={inputRef}
      />
    </li>
  );
}

// examples/todo-mvc-svelte/src/Todo.svelte
<script>
  import { tick } from 'svelte';

  export let actor = null;

  const { send } = actor;
  $: ({ id, title, completed } = $actor.context);

  $: $actor.actions && select();

  let inputNode = null;
  async function select() {
    if (
      inputNode &&
      $actor.actions.find((action) => action.type === 'focusInput')
    ) {
      await tick();
      inputNode.select();
    }
  }

  function handleKeydown(event) {
    switch (event.key) {
      case 'Enter':
        send('COMMIT');
        break;
      case 'Escape':
        send('CANCEL');
        break;
    }
  }
</script>

<li
  class="todo"
  class:editing={$actor.matches('editing')}
  class:completed
  data-todo-state={completed ? 'completed' : 'active'}
>
  <div class="view">
    <input
      class="toggle"
      type="checkbox"
      on:change={() => send('TOGGLE_COMPLETE')}
      checked={completed}
    />
    <label for="edit-{id}" on:dblclick={() => send('EDIT')}>{title}</label>
    <button class="destroy" on:click={() => send('DELETE')} />
  </div>

  <input
    id="edit-{id}"
    class="edit"
    type="text"
    value={title}
    on:blur={() => send('BLUR')}
    on:input={(event) => send({ type: 'CHANGE', value: event.target.value })}
    on:keydown={handleKeydown}
    bind:this={inputNode}
  />
</li>
