// packages/xstate-react/src/useActorRef.ts
import { useEffect, useState } from 'react';
import useIsomorphicLayoutEffect from 'use-isomorphic-layout-effect';
import {
  Actor,
  ActorOptions,
  AnyActorLogic,
  AnyStateMachine,
  Observer,
  SnapshotFrom,
  createActor,
  toObserver,
  type ConditionalRequired,
  type IsNotNever,
  type RequiredOptions
} from 'xstate';
import { stopRootWithRehydration } from './stopRootWithRehydration';

export function useIdleActorRef<TLogic extends AnyActorLogic>(
  logic: TLogic,
  ...[options]: ConditionalRequired<
    [
      options?: ActorOptions<TLogic> & {
        [K in RequiredOptions<TLogic>]: unknown;
      }
    ],
    IsNotNever<RequiredOptions<TLogic>>
  >
): Actor<TLogic> {
  let [[currentConfig, actorRef], setCurrent] = useState(() => {
    const actorRef = createActor(logic, options);
    return [logic.config, actorRef];
  });

  if (logic.config !== currentConfig) {
    const newActorRef = createActor(logic, {
      ...options,
      snapshot: (actorRef.getPersistedSnapshot as any)({
        __unsafeAllowInlineActors: true
      })
    });
    setCurrent([logic.config, newActorRef]);
    actorRef = newActorRef;
  }

  // TODO: consider using `useAsapEffect` that would do this in `useInsertionEffect` is that's available
  useIsomorphicLayoutEffect(() => {
    (actorRef.logic as any as AnyStateMachine).implementations = (
      logic as any as AnyStateMachine
    ).implementations;
  });

  return actorRef;
}

export function useActorRef<TLogic extends AnyActorLogic>(
  machine: TLogic,
  options: ActorOptions<TLogic> = {},
  observerOrListener?:
    | Observer<SnapshotFrom<TLogic>>
    | ((value: SnapshotFrom<TLogic>) => void)
): Actor<TLogic> {
  const actorRef = useIdleActorRef(machine, options);

  useEffect(() => {
    if (!observerOrListener) {
      return;
    }
    let sub = actorRef.subscribe(toObserver(observerOrListener));
    return () => {
      sub.unsubscribe();
    };
  }, [observerOrListener]);

  useEffect(() => {
    actorRef.start();

    return () => {
      stopRootWithRehydration(actorRef);
    };
  }, [actorRef]);

  return actorRef;
}

// packages/xstate-angular/src/useActorRef.ts
import {
  Actor,
  ActorOptions,
  AnyActorLogic,
  createActor,
  Observer,
  SnapshotFrom,
  Subscription,
  toObserver
} from 'xstate';
import { DestroyRef, inject } from '@angular/core';

export function useActorRef<TLogic extends AnyActorLogic>(
  actorLogic: TLogic,
  options: ActorOptions<TLogic> = {},
  observerOrListener?:
    | Observer<SnapshotFrom<TLogic>>
    | ((value: SnapshotFrom<TLogic>) => void)
): Actor<TLogic> {
  const actorRef = createActor(actorLogic, options);

  let sub: Subscription;
  if (observerOrListener) {
    sub = actorRef.subscribe(toObserver(observerOrListener));
  }

  actorRef.start();
  inject(DestroyRef).onDestroy(() => {
    actorRef.stop();
    sub?.unsubscribe();
  });

  return actorRef;
}
