// examples/template-react-ts/src/App.tsx
import React from 'react';
import './App.css';
import { useMachine } from '@xstate/react';
import { toggleMachine } from './toggle.machine';

function App() {
  const [state, send] = useMachine(toggleMachine);
  const active = state.matches('active');
  const { count } = state.context;

  return (
    <div className="app">
      <h1>XState React Template</h1>
      <h2>Fork this template!</h2>
      <button onClick={() => send('TOGGLE')}>
        Click me ({active ? '✅' : '❌'})
      </button>{' '}
      <code>
        Toggled <strong>{count}</strong> times
      </code>
    </div>
  );
}

export default App;

// examples/template-angular-ts/src/app/app.component.ts
import { Component } from '@angular/core';
import { toggleMachine } from 'src/toggle.machine';
import { interpret } from 'xstate';

@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  actor = interpret(toggleMachine).start();
}

<div id="app">
  <h1>XState Angular Template</h1>
  <h2>Fork this template!</h2>
  <button type="button" (click)="actor.send('TOGGLE')">
    Click me ({{ actor.state.matches('active') ? '✅' : '❌' }})
  </button>
  <code>
    Toggled
    <strong>{{ actor.state.context.count }}</strong> times
  </code>
</div>
