// packages/xstate-store-solid/src/index.ts
/* @jsxImportSource solid-js */
export * from '@xstate/store';

import { createEffect, createSignal, onCleanup } from 'solid-js';
import {
  createStore,
  type AnyStoreLogicCreator,
  type InputFromStoreLogicCreator,
  type Readable,
  type Store,
  type StoreConfig,
  type StoreFromStoreLogicCreator
} from '@xstate/store';

function defaultCompare<T>(a: T | undefined, b: T) {
  return a === b;
}

type AnyStoreConfig = StoreConfig<any, any, any, any, any, any>;

type StoreFromDefinition<TDefinition extends AnyStoreConfig> =
  TDefinition extends StoreConfig<infer TContext, infer TEventPayloadMap, any>
    ? Store<TContext, TEventPayloadMap, any>
    : never;

type StoreDefinition = AnyStoreConfig | AnyStoreLogicCreator;

type StoreFromStoreDefinition<TDefinition extends StoreDefinition> =
  TDefinition extends AnyStoreLogicCreator
    ? StoreFromStoreLogicCreator<TDefinition>
    : TDefinition extends AnyStoreConfig
      ? StoreFromDefinition<TDefinition>
      : never;

type UseStoreArgs<TDefinition extends StoreDefinition> =
  TDefinition extends AnyStoreLogicCreator
    ? undefined extends InputFromStoreLogicCreator<TDefinition>
      ? [logic: TDefinition, input?: InputFromStoreLogicCreator<TDefinition>]
      : [logic: TDefinition, input: InputFromStoreLogicCreator<TDefinition>]
    : [definition: TDefinition];

function useSelectorWithCompare<TSnapshot, T>(
  selector: (snapshot: TSnapshot) => T,
  compare: (a: T | undefined, b: T) => boolean
): (snapshot: TSnapshot) => T {
  let previous: T | undefined;

  return (state): T => {
    const next = selector(state);

    if (previous === undefined || !compare(previous, next)) {
      previous = next;
    }

    return previous;
  };
}

/**
 * Creates a selector which subscribes to the store and selects a value from the
 * store's snapshot, using an optional comparison function.
 *
 * @example
 *
 * ```tsx
 * import { donutStore } from './donutStore.ts';
 * import { useSelector } from '@xstate/store-solid';
 *
 * function DonutCounter() {
 *   const donutCount = useSelector(donutStore, (state) => state.context.donuts);
 *
 *   return (
 *     <div>
 *       <button onClick={() => donutStore.send({ type: 'addDonut' })}>
 *         Add donut ({donutCount()})
 *       </button>
 *     </div>
 *   );
 * }
 * ```
 *
 * @param store The store, created from `createStore(…)`
 * @param selector A function which takes in the snapshot and returns a selected
 *   value from it
 * @param compare An optional function which compares the selected value to the
 *   previously selected value
 * @returns A read-only signal of the selected value
 */
export function useSelector<TSnapshot, T>(
  store: Readable<TSnapshot>,
  selector: (snapshot: TSnapshot) => T,
  compare: (a: T | undefined, b: T) => boolean = defaultCompare
): () => T {
  const selectorWithCompare = useSelectorWithCompare(selector, compare);
  const [selectedValue, setSelectedValue] = createSignal(
    selectorWithCompare(store.get())
  );

  createEffect(() => {
    const subscription = store.subscribe(() => {
      const newValue = selectorWithCompare(store.get());
      setSelectedValue(() => newValue);
    });

    onCleanup(() => {
      subscription.unsubscribe();
    });
  });

  return selectedValue;
}

export function useStore<TDefinition extends StoreDefinition>(
  ...[definition, input]: UseStoreArgs<TDefinition>
): StoreFromStoreDefinition<TDefinition> {
  return (
    'createStore' in definition
      ? definition.createStore(input)
      : createStore(definition)
  ) as StoreFromStoreDefinition<TDefinition>;
}

// packages/xstate-store-angular/src/index.ts
export * from '@xstate/store';

import {
  DestroyRef,
  Injector,
  assertInInjectionContext,
  inject,
  linkedSignal,
  runInInjectionContext
} from '@angular/core';
import type { Signal } from '@angular/core';
import { type Readable } from '@xstate/store';

function defaultCompare<T>(a: T, b: T) {
  return a === b;
}

/**
 * An Angular function that creates a signal subscribed to a store, selecting a
 * value via an optional selector function.
 *
 * @example
 *
 * ```ts
 * import { Component } from '@angular/core';
 * import { store } from './store';
 * import { injectStore } from '@xstate/store-angular';
 *
 * @Component({
 *   selector: 'app-counter',
 *   template: `<div>{{ count() }}</div>`
 * })
 * export class CounterComponent {
 *   count = injectStore(store, (state) => state.context.count);
 * }
 * ```
 *
 * @param store The store, created from `createStore(…)`
 * @param selector A function which takes in the snapshot and returns a selected
 *   value
 * @param compare An optional function which compares the selected value to the
 *   previous value
 * @returns A readonly Signal of the selected value
 */
export function injectStore<TStore extends Readable<any>, TSelected>(
  store: TStore,
  selector?: (state: TStore extends Readable<infer T> ? T : never) => TSelected,
  compare?: (a: TSelected, b: TSelected) => boolean
): Signal<TSelected>;
export function injectStore<TStore extends Readable<any>, TSelected>(
  store: TStore,
  selector: (
    state: TStore extends Readable<infer T> ? T : never
  ) => TSelected = (d) => d as TSelected,
  compare: (a: TSelected, b: TSelected) => boolean = defaultCompare
): Signal<TSelected> {
  assertInInjectionContext(injectStore);
  const injector = inject(Injector);

  return runInInjectionContext(injector, () => {
    const destroyRef = inject(DestroyRef);
    const slice = linkedSignal(() => selector(store.get()), { equal: compare });

    const { unsubscribe } = store.subscribe((s) => {
      slice.set(selector(s));
    });

    destroyRef.onDestroy(() => {
      unsubscribe();
    });

    return slice.asReadonly();
  });
}
