// examples/todo-mvc-svelte/src/Todos.svelte
<script>
  import { tick } from 'svelte';

  import Todo from './Todo.svelte';

  import { todosMachine } from './todos.machine';
  import { useMachine } from '@xstate/svelte';

  const { state, send, service } = useMachine(todosMachine, { devTools: true });

  $: ({ todo, todos, filter } = $state.context);

  $: numActiveTodos = todos.filter((todo) => !todo.completed).length;
  $: allCompleted = todos.length > 0 && numActiveTodos === 0;
  $: mark = !allCompleted ? 'completed' : 'active';
  $: markEvent = `MARK.${mark}`;
  $: filteredTodos = filterTodos(filter, todos);

  function filterTodos(filter, todos) {
    switch (filter) {
      case 'active':
        return todos.filter((todo) => !todo.completed);
      case 'completed':
        return todos.filter((todo) => todo.completed);
      default:
        return todos;
    }
  }

  function handleKeydown(event) {
    if (event.key === 'Enter') {
      send({ type: 'NEWTODO.COMMIT', value: event.target.value });
    }
  }

  function handleHashchange() {
    send({ type: 'SHOW', filter: window.location.hash.slice(2) || 'all' });
  }

  async function autofocus(node) {
    await tick();
    node.focus();
  }
</script>

<svelte:window on:hashchange={handleHashchange} />

<section class="todoapp" data-state={$state.toStrings()}>
  <header class="header">
    <h1>Todos</h1>
    <input
      class="new-todo"
      type="text"
      placeholder="What needs to be done?"
      on:input={(event) => {
        send({ type: 'NEWTODO.CHANGE', value: event.target.value });
      }}
      on:keydown={handleKeydown}
      value={todo}
      use:autofocus
    />
  </header>
  <section class="main">
    <input
      id="toggle-all"
      class="toggle-all"
      type="checkbox"
      checked={allCompleted}
      on:change={() => send(markEvent)}
    />
    <label for="toggle-all" title="Mark all as {mark}">Mark all as {mark}</label
    >
    <ul class="todo-list">
      {#each filteredTodos as filteredTodo (filteredTodo.id)}
        <Todo actor={filteredTodo.ref} />
      {/each}
    </ul>

    {#if todos.length > 0}
      <footer class="footer">
        <span class="todo-count">
          <strong>
            {numActiveTodos} item{numActiveTodos === 1 ? '' : 's'}
            left
          </strong>
        </span>
        <ul class="filters">
          <li>
            <a href="#/" class:selected={filter === 'all'}>All</a>
          </li>
          <li>
            <a href="#/active" class:selected={filter === 'active'}>Active</a>
          </li>
          <li>
            <a href="#/completed" class:selected={filter === 'completed'}
              >Completed</a
            >
          </li>
        </ul>
        {#if numActiveTodos < todos.length}
          <button
            class="clear-completed"
            on:click={() => send('CLEAR_COMPLETED')}>Clear completed</button
          >
        {/if}
      </footer>
    {/if}
  </section>
</section>

// examples/todo-mvc-vue/src/Todos.vue
<template>
  <section class="todoapp" :data-state="state.toStrings()">
    <header class="header">
      <h1>Todos</h1>
      <input
        class="new-todo"
        autofocus
        type="text"
        placeholder="What needs to be done?"
        @keypress.enter="
          send({ type: 'NEWTODO.COMMIT', value: $event.target.value })
        "
        @input="send({ type: 'NEWTODO.CHANGE', value: $event.target.value })"
        :value="todo"
      />
    </header>
    <section class="main">
      <input
        id="toggle-all"
        class="toggle-all"
        type="checkbox"
        :checked="allCompleted"
        @change="send(markEvent)"
      />
      <label for="toggle-all" :title="`Mark all as ${mark}`"
        >Mark all as {{ mark }}</label
      >
      <ul class="todo-list">
        <TodoItem
          v-for="todoItem in filteredTodos"
          :key="todoItem.id"
          :todo-ref="todoItem.ref"
        ></TodoItem>
      </ul>
      <footer class="footer" v-show="todos.length">
        <span class="todo-count">
          <strong>
            {{ numActiveTodos }} item{{ numActiveTodos === 1 ? '' : 's' }}
            left
          </strong>
        </span>
        <ul class="filters">
          <li>
            <a
              href="#/"
              :class="{
                selected: filter === 'all'
              }"
              >All</a
            >
          </li>
          <li>
            <a
              href="#/active"
              :class="{
                selected: filter === 'active'
              }"
              >Active</a
            >
          </li>
          <li>
            <a
              href="#/completed"
              :class="{
                selected: filter === 'completed'
              }"
              >Completed</a
            >
          </li>
        </ul>
        <button
          v-show="numActiveTodos < todos.length"
          class="clear-completed"
          @click="send('CLEAR_COMPLETED')"
        >
          Clear completed
        </button>
      </footer>
    </section>
  </section>
</template>
<script setup lang="ts">
import TodoItem from './TodoItem.vue';
import { todosMachine } from './todos.machine';
import { useMachine } from '@xstate/vue';
import { computed } from 'vue';

import { useHashChange } from './useHashChange';

function filterTodos(filter, todos) {
  if (filter === 'active') {
    return todos.filter((todo) => !todo.completed);
  }
  if (filter === 'completed') {
    return todos.filter((todo) => todo.completed);
  }
  return todos;
}

const { state, send } = useMachine(todosMachine, { devTools: true });

const todos = computed(() => state.value.context.todos);
const todo = computed(() => state.value.context.todo);
const filter = computed(() => state.value.context.filter);

useHashChange(() =>
  send({ type: 'SHOW', filter: window.location.hash.slice(2) || 'all' })
);

const numActiveTodos = computed(
  () => todos.value.filter((todo) => !todo.completed).length
);
const allCompleted = computed(
  () => todos.value.length > 0 && numActiveTodos.value === 0
);
const mark = computed(() => (!allCompleted.value ? 'completed' : 'active'));
const markEvent = computed(() => `MARK.${mark.value}`);
const filteredTodos = computed(() => filterTodos(filter.value, todos.value));
</script>
