// examples/todo-mvc-react/src/Todos.jsx
import React, { useEffect, useRef } from 'react';
import cn from 'classnames';
import { useMachine } from '@xstate/react';
import { useHashChange } from './useHashChange';
import { Todo } from './Todo';
import { todosMachine } from './todos.machine';

function filterTodos(filter, todos) {
  if (filter === 'active') {
    return todos.filter((todo) => !todo.completed);
  }

  if (filter === 'completed') {
    return todos.filter((todo) => todo.completed);
  }

  return todos;
}

const persistedTodosMachine = todosMachine.withConfig(
  {
    actions: {
      persist: (context) => {
        try {
          localStorage.setItem('todos-xstate', JSON.stringify(context.todos));
        } catch (e) {
          console.error(e);
        }
      }
    }
  },
  // initial state from localstorage
  {
    todo: 'Learn state machines',
    todos: (() => {
      try {
        return JSON.parse(localStorage.getItem('todos-xstate')) || [];
      } catch (e) {
        console.error(e);
        return [];
      }
    })(),
    filter: 'all'
  }
);

export function Todos() {
  const [state, send] = useMachine(persistedTodosMachine, { devTools: true });

  useHashChange(() => {
    send({ type: 'SHOW', filter: window.location.hash.slice(2) || 'all' });
  });

  // Capture initial state of browser hash
  useEffect(() => {
    window.location.hash.slice(2) &&
      send({ type: 'SHOW', filter: window.location.hash.slice(2) });
  }, [send]);

  const { todo, todos, filter } = state.context;

  const numActiveTodos = todos.filter((todo) => !todo.completed).length;
  const allCompleted = todos.length > 0 && numActiveTodos === 0;
  const mark = !allCompleted ? 'completed' : 'active';
  const markEvent = `MARK.${mark}`;
  const filteredTodos = filterTodos(filter, todos);

  const inputRef = useRef(null);
  useEffect(() => {
    if (todos.length === 0) {
      inputRef.current.focus();
    }
  }, [todos]);

  return (
    <section className="todoapp" data-state={state.toStrings()}>
      <header className="header">
        <h1>todos</h1>
        <input
          ref={inputRef}
          className="new-todo"
          placeholder="What needs to be done?"
          autoFocus
          onKeyPress={(e) => {
            if (e.key === 'Enter') {
              send({ type: 'NEWTODO.COMMIT', value: e.target.value });
            }
          }}
          onChange={(e) =>
            send({ type: 'NEWTODO.CHANGE', value: e.target.value })
          }
          value={todo}
        />
      </header>

      {!!todos.length && (
        <>
          <section className="main">
            <input
              id="toggle-all"
              className="toggle-all"
              type="checkbox"
              checked={allCompleted}
              onChange={() => {
                send(markEvent);
              }}
            />
            <label htmlFor="toggle-all" title={`Mark all as ${mark}`}>
              Mark all as {mark}
            </label>
            <ul className="todo-list">
              {filteredTodos.map((todo) => (
                <Todo key={todo.id} todoRef={todo.ref} />
              ))}
            </ul>
          </section>

          <footer className="footer">
            <span className="todo-count">
              <strong>{numActiveTodos}</strong> item
              {numActiveTodos === 1 ? '' : 's'} left
            </span>
            <ul className="filters">
              <li>
                <a
                  className={cn({
                    selected: filter === 'all'
                  })}
                  href="#/"
                >
                  All
                </a>
              </li>
              <li>
                <a
                  className={cn({
                    selected: filter === 'active'
                  })}
                  href="#/active"
                >
                  Active
                </a>
              </li>
              <li>
                <a
                  className={cn({
                    selected: filter === 'completed'
                  })}
                  href="#/completed"
                >
                  Completed
                </a>
              </li>
            </ul>
            {numActiveTodos < todos.length && (
              <button
                onClick={(_) => send('CLEAR_COMPLETED')}
                className="clear-completed"
              >
                Clear completed
              </button>
            )}
          </footer>
        </>
      )}
    </section>
  );
}

// examples/todo-mvc-vue/src/Todos.vue
<template>
  <section class="todoapp" :data-state="state.toStrings()">
    <header class="header">
      <h1>Todos</h1>
      <input
        class="new-todo"
        autofocus
        type="text"
        placeholder="What needs to be done?"
        @keypress.enter="
          send({ type: 'NEWTODO.COMMIT', value: $event.target.value })
        "
        @input="send({ type: 'NEWTODO.CHANGE', value: $event.target.value })"
        :value="todo"
      />
    </header>
    <section class="main">
      <input
        id="toggle-all"
        class="toggle-all"
        type="checkbox"
        :checked="allCompleted"
        @change="send(markEvent)"
      />
      <label for="toggle-all" :title="`Mark all as ${mark}`"
        >Mark all as {{ mark }}</label
      >
      <ul class="todo-list">
        <TodoItem
          v-for="todoItem in filteredTodos"
          :key="todoItem.id"
          :todo-ref="todoItem.ref"
        ></TodoItem>
      </ul>
      <footer class="footer" v-show="todos.length">
        <span class="todo-count">
          <strong>
            {{ numActiveTodos }} item{{ numActiveTodos === 1 ? '' : 's' }}
            left
          </strong>
        </span>
        <ul class="filters">
          <li>
            <a
              href="#/"
              :class="{
                selected: filter === 'all'
              }"
              >All</a
            >
          </li>
          <li>
            <a
              href="#/active"
              :class="{
                selected: filter === 'active'
              }"
              >Active</a
            >
          </li>
          <li>
            <a
              href="#/completed"
              :class="{
                selected: filter === 'completed'
              }"
              >Completed</a
            >
          </li>
        </ul>
        <button
          v-show="numActiveTodos < todos.length"
          class="clear-completed"
          @click="send('CLEAR_COMPLETED')"
        >
          Clear completed
        </button>
      </footer>
    </section>
  </section>
</template>
<script setup lang="ts">
import TodoItem from './TodoItem.vue';
import { todosMachine } from './todos.machine';
import { useMachine } from '@xstate/vue';
import { computed } from 'vue';

import { useHashChange } from './useHashChange';

function filterTodos(filter, todos) {
  if (filter === 'active') {
    return todos.filter((todo) => !todo.completed);
  }
  if (filter === 'completed') {
    return todos.filter((todo) => todo.completed);
  }
  return todos;
}

const { state, send } = useMachine(todosMachine, { devTools: true });

const todos = computed(() => state.value.context.todos);
const todo = computed(() => state.value.context.todo);
const filter = computed(() => state.value.context.filter);

useHashChange(() =>
  send({ type: 'SHOW', filter: window.location.hash.slice(2) || 'all' })
);

const numActiveTodos = computed(
  () => todos.value.filter((todo) => !todo.completed).length
);
const allCompleted = computed(
  () => todos.value.length > 0 && numActiveTodos.value === 0
);
const mark = computed(() => (!allCompleted.value ? 'completed' : 'active'));
const markEvent = computed(() => `MARK.${mark.value}`);
const filteredTodos = computed(() => filterTodos(filter.value, todos.value));
</script>
