// packages/xstate-angular/src/useActorRef.ts
import {
  Actor,
  ActorOptions,
  AnyActorLogic,
  createActor,
  Observer,
  SnapshotFrom,
  Subscription,
  toObserver
} from 'xstate';
import { DestroyRef, inject } from '@angular/core';

export function useActorRef<TLogic extends AnyActorLogic>(
  actorLogic: TLogic,
  options: ActorOptions<TLogic> = {},
  observerOrListener?:
    | Observer<SnapshotFrom<TLogic>>
    | ((value: SnapshotFrom<TLogic>) => void)
): Actor<TLogic> {
  const actorRef = createActor(actorLogic, options);

  let sub: Subscription;
  if (observerOrListener) {
    sub = actorRef.subscribe(toObserver(observerOrListener));
  }

  actorRef.start();
  inject(DestroyRef).onDestroy(() => {
    actorRef.stop();
    sub?.unsubscribe();
  });

  return actorRef;
}

// packages/xstate-solid/src/useActorRef.ts
import { onCleanup, onMount } from 'solid-js';
import type { ActorOptions, ActorRefFrom, AnyActorLogic } from 'xstate';
import { createActor } from 'xstate';

export function useActorRef<TLogic extends AnyActorLogic>(
  logic: TLogic,
  options?: ActorOptions<TLogic>
): ActorRefFrom<TLogic> {
  const actorRef = createActor(logic, options);

  onMount(() => {
    actorRef.start();
    onCleanup(() => actorRef.stop());
  });

  return actorRef as any;
}
